drop view if exists la_pampa;
create view la_pampa as (
select 
a."id_Prestacion" as id_prestacion,
CAST ( a."Codigo_Prestacion" as character varying(11)) as prestacion_codigo,
CAST ( a."Cuie_Efector" as character(6)) as cuie,
CAST ( a."Fecha_Prestacion" as date) as prestacion_fecha,
CAST ( a."Apellido_Beneficiario" as character varying(100)) as beneficiario_apellido,
CAST ( a."Nombre_Beneficiario" as character varying(100)) as beneficiario_nombre,
CAST ( a."clave_Beneficiario" as character varying(16)) as beneficiario_clave,
CAST ( a."BENEF_TIPO_DOCUMENTO" as character(3)) as beneficiario_tipo_documento,
CAST ( a."BENEF_CLASE_DOCUMENTO" as character(1)) as beneficiario_clase_documento,
CAST ( a."BENEF_NUMERO_DOCUMENTO" as character varying(14)) as beneficiario_nro_documento,
CAST ( a."SEXO" as character(1)) as beneficiario_sexo,
CAST ( a."FECHA_DE_NACIMIENTO" as date) as beneficiario_nacimiento,
CAST ( a."VALOR_UNITARIO" as numeric(9,2)) as valor_unitario_facturado,
CAST ( a."CANTIDAD" as integer) as cantidad_facturado,
null as importe_prestacion_facturado,
null as id_factura,
CAST ( a."NUM_FACTURA" as character varying(100)) as factura_nro,
CAST ( a."FECHA_FACTURA" AS date) as factura_fecha,
CAST ( a."IMPORTE_FACTURADO" as numeric(9,2)) as factura_importe_total,
null as factura_fecha_recepcion,
null as alta_complejidad,
null as id_liquidacion,
CAST ( a."FECHA_LIQUIDACION" as date) as liquidacion_fecha,
null as valor_unitario_aprobado,
null as cantidad_aprobada,
null as importe_prestacion_aprobado,
null as numero_comprobante_extracto_bancario,
cast(p.id1 as integer) as id_dato_reportable_1,
cast(p.dato_id1 as character varying(255))as dato_reportable_1,
cast(p.id2 as integer) as id_dato_reportable_2,
cast(p.dato_id2 as character varying(255)) as dato_reportable_2,
cast(p.id3 as integer) as id_dato_reportable_3,
cast(p.dato_id3 as character varying(255)) as dato_reportable_3,
cast(p.id4 as integer) as id_dato_reportable_4,
cast(p.dato_id4 as character varying(255)) as dato_reportable_4,
null as id_dato_reportable_5,
null as dato_reportable_5,
null as id_op,
null as numero_op,
null as fecha_op,
null as importe_total_op,
CAST ( a."NUMERO_EXP" as character varying(100)) as numero_expte,
null as fecha_debito_bancario,
null as importe_debito_bancario,
null as fecha_notificacion_efector
from la_pampa_prestaciones p
join la_pampa_auditoria a on a."id_Prestacion" = p.id_prest
);
